name: Publish library to NPM

on:
  release:
    types: [created]

jobs:
  ci_tests:
    uses: ./.github/workflows/ci_tests.yml

  ci_publish:
    needs: ci_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm clean-install --engine-strict

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
        run: npm publish --access public
